# Generated by Django 4.2 on 2024-07-17 15:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('news', '0003_contactus_news_category_news_is_editorial_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='posted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='newsrepoter', to=settings.AUTH_USER_MODEL),
        ),
    ]
